/* Aca es el primer arreglo que use para el main.js despues lo pase a json pero no tuve tiempo de cambiar el codigo en el main.js para terminar eliminando este, asi que aca queda */

const products = [
    {
    "id": 1,
    "title": "Laptop Acer Aspire 3",
    "price": 109.95,
    "oferta": true,
    "description": "Full HD IPS Display | AMD Ryzen 3 7320U Quad-Core Processor | AMD Radeon Graphics | 8GB LPDDR5 | 128GB NVMe SSD | Wi-Fi 6 | Windows 11 Home in S Mode",
    "category": "electronics",
    "image": "https://m.media-amazon.com/images/I/71+1lOl1Y1L._AC_SX679_.jpg"
    },
    {
    "id": 2,
    "title": "Amazon Basics Wireless Computer Mouse",
    "price": 22.3,
    "oferta": false,
    "description": "Smooth, precise and affordable wireless optical 3-button mouse with USB nano receiver for laptop, desktop and netbook PCs",
    "category": "electronics",
    "image": "https://m.media-amazon.com/images/I/61YQeAUIboL._AC_SX466_.jpg",
    },
    {
    "id": 3,
    "title": "TP-Link WiFi Extender",
    "price": 55.99,
    "oferta": false,
    "description": "Extend Wi-Fi Coverage : Boost Internet Wi-Fi Coverage up to 1500 Square feet and connects up to 30 devices - Compatible with any Wifi Router or access point",
    "category": "electronics",
    "image": "https://m.media-amazon.com/images/I/51IyLLCsibL._AC_SX466_.jpg",
    },
    {
    "id": 4,
    "title": "Cat 7 Ethernet Patch Cable",
    "price": 15.99,
    "oferta": false,
    "description": "25 foot Cat-7 STP (Shield Twisted Pair) ethernet cables for connecting networked devices such as computers, printers, routers, and more",
    "category": "electronics",
    "image": "https://m.media-amazon.com/images/I/71tY698ujsL._AC_SX466_.jpg",
    },
    {
    "id": 5,
    "title": "Sceptre 24-inch LED Monitor",
    "price": 695,
    "oferta": true,
    "description": "99% sRGB: With 99% sRGB, this monitor offers a wider color gamut than most conventional monitors, giving deeper colors and defining features.",
    "category": "electronics",
    "image": "https://m.media-amazon.com/images/I/71vRYxuUa6L.__AC_SX300_SY300_QL70_FMwebp_.jpg",
    },
    {
    "id": 6,
    "title": "AMD Ryzen 7 7800X3D 8-Core",
    "price": 168,
    "oferta": false,
    "description": "Processor provides dependable and fast execution of tasks with maximum efficiency.Graphics Frequency : 2200 MHZ.Number of CPU Cores : 8. Maximum Operating Temperature (Tjmax) : 89°C.",
    "category": "electronics",
    "image": "https://m.media-amazon.com/images/I/51HqC0rU9HL._AC_SX466_.jpg",
    },
    {
    "id": 7,
    "title": "SAMSUNG EVO Select Micro SD-Memory-Card",
    "price": 9.99,
    "oferta": false,
    "description": "ALL THE SPACE YOU NEED: Store tons of media on your phone, load games or download more apps on your tablet at top-notch speed, making transfers seamless and reliable",
    "category": "electronics",
    "image": "https://m.media-amazon.com/images/I/71tK21fYkDL._AC_SX466_.jpg",
    },
    {
    "id": 8,
    "title": "Intel Core i7-13700K",
    "price": 10.99,
    "oferta": true,
    "description": "13th Gen Intel Core processors offer revolutionary design for beyond real-world performance. From extreme multitasking, immersive streaming, and faster creating, do what you do",
    "category": "electronics",
    "image": "https://m.media-amazon.com/images/I/61m0zH-NiTL._AC_SX679_.jpg",
    },
    {
    "id": 9,
    "title": "WD 2TB Elements Portable External Hard Drive - USB 3.0",
    "price": 64,
    "oferta": true,
    "description": "USB 3.0 and USB 2.0 Compatibility Fast data transfers Improve PC Performance High Capacity; Compatibility Formatted NTFS for Windows 10, Windows 8.1, Windows 7; Reformatting may be required for other operating systems; Compatibility may vary depending on users hardware configuration and operating system",
    "category": "electronics",
    "image": "https://fakestoreapi.com/img/61IBBVJvSDL._AC_SY879_.jpg",
    },
    {
    "id": 10,
    "title": "SanDisk SSD PLUS 1TB Internal SSD - SATA III 6 Gb/s",
    "price": 109,
    "oferta": true,
    "description": "Easy upgrade for faster boot up, shutdown, application load and response (As compared to 5400 RPM SATA 2.5” hard drive; Based on published specifications and internal benchmarking tests using PCMark vantage scores) Boosts burst write performance, making it ideal for typical PC workloads The perfect balance of performance and reliability Read/write speeds of up to 535MB/s/450MB/s (Based on internal testing; Performance may vary depending upon drive capacity, host device, OS and application.)",
    "category": "electronics",
    "image": "https://fakestoreapi.com/img/61U7T1koQqL._AC_SX679_.jpg",
    },
    {
    "id": 11,
    "title": "Silicon Power 256GB SSD 3D NAND A55 SLC Cache Performance Boost SATA III 2.5",
    "price": 109,
    "oferta": false,
    "description": "3D NAND flash are applied to deliver high transfer speeds Remarkable transfer speeds that enable faster bootup and improved overall system performance. The advanced SLC Cache Technology allows performance boost and longer lifespan 7mm slim design suitable for Ultrabooks and Ultra-slim notebooks. Supports TRIM command, Garbage Collection technology, RAID, and ECC (Error Checking & Correction) to provide the optimized performance and enhanced reliability.",
    "category": "electronics",
    "image": "https://fakestoreapi.com/img/71kWymZ+c+L._AC_SX679_.jpg",
    },
    {
    "id": 12,
    "title": "WD 4TB Gaming Drive Works with Playstation 4 Portable External Hard Drive",
    "price": 114,
    "oferta": false,
    "description": "Expand your PS4 gaming experience, Play anywhere Fast and easy, setup Sleek design with high capacity, 3-year manufacturer's limited warranty",
    "category": "electronics",
    "image": "https://fakestoreapi.com/img/61mtL65D4cL._AC_SX679_.jpg",
    },
    {
    "id": 13,
    "title": "Acer SB220Q bi 21.5 inches Full HD (1920 x 1080) IPS Ultra-Thin",
    "price": 599,
    "oferta": false,
    "description": "21. 5 inches Full HD (1920 x 1080) widescreen IPS display And Radeon free Sync technology. No compatibility for VESA Mount Refresh Rate: 75Hz - Using HDMI port Zero-frame design | ultra-thin | 4ms response time | IPS panel Aspect ratio - 16: 9. Color Supported - 16. 7 million colors. Brightness - 250 nit Tilt angle -5 degree to 15 degree. Horizontal viewing angle-178 degree. Vertical viewing angle-178 degree 75 hertz",
    "category": "electronics",
    "image": "https://fakestoreapi.com/img/81QpkIctqPL._AC_SX679_.jpg",
    },
    {
    "id": 14,
    "title": "Samsung 49-Inch CHG90 144Hz Curved Gaming Monitor (LC49HG90DMNXZA)  Super Ultrawide Screen QLED ",
    "price": 999.99,
    "oferta": true,
    "description": "49 INCH SUPER ULTRAWIDE 32:9 CURVED GAMING MONITOR with dual 27 inch screen side by side QUANTUM DOT (QLED) TECHNOLOGY, HDR support and factory calibration provides stunningly realistic and accurate color and contrast 144HZ HIGH REFRESH RATE and 1ms ultra fast response time work to eliminate motion blur, ghosting, and reduce input lag",
    "category": "electronics",
    "image": "https://fakestoreapi.com/img/81Zt42ioCgL._AC_SX679_.jpg",
    },
    {
    "id": 15,
    "title": "SAMSUNG Galaxy Android Tablet",
    "price": 56.99,
    "oferta": false,
    "description": "A SCREEN EVERYONE WILL LOVE: Whether your family is streaming or video chatting with friends, the Galaxy Tab A8 tablet brings out the best in every moment on a 10.5",
    "category": "electronics",
    "image": "https://m.media-amazon.com/images/I/61krikJxTmL._AC_SX466_.jpg",
    },
    {
    "id": 16,
    "title": "SteelSeries Gaming Headset",
    "price": 29.95,
    "oferta": false,
    "description": "Almighty Audio - Experience ultimate clarity and sound quality with Premium High Fidelity Drivers. Fully customize the sound experience with the Sonar Software by using a first-in-gaming Pro-grade Parametric EQ..Note : If the size of the earbud tips does not match the size of your ear canals or the headset is not worn properly in your ears, you may not obtain the correct sound qualities or call performance. Change the earbud tips to ones that fit more snugly in your ear",
    "category": "electronics",
    "image": "https://m.media-amazon.com/images/I/71fz1tjzJUL._AC_SX466_.jpg",
    },
    {
    "id": 17,
    "title": "Amazon Basics USB Speakers for PC",
    "price": 39.99,
    "oferta": true,
    "description": "External computer speaker in Black (set of 2) for amplifying PC or laptop audio",
    "category": "electronics",
    "image": "https://m.media-amazon.com/images/I/81l54Su1w4L._AC_SX466_.jpg",
    },
    {
    "id": 18,
    "title": "TP-Link USB WiFi Adapter for PC",
    "price": 9.85,
    "oferta": false,
    "description": "Wireless Network Adapter for Desktop with 2.4GHz, 5GHz High Gain Dual Band 5dBi Antenna, Supports Win11/10/8.1/8/7/XP, Mac OS 10.9-10.14",
    "category": "electronics",
    "image": "https://m.media-amazon.com/images/I/41Qo0EGG4TL._AC_SX466_.jpg",
    },
    {
    "id": 19,
    "title": "Premium Performance Thermal Paste for All Processors",
    "price": 7.95,
    "oferta": false,
    "description": "Very high Thermal Conductivity, Long Durability, Safe Application, Non-Conductive, CPU Thermal",
    "category": "electronics",
    "image": "https://m.media-amazon.com/images/I/61j5yphfhXL._AC_SX466_.jpg",
    },
    {
    "id": 20,
    "title": "GIGABYTE Z790 AORUS Elite AX Motherboard",
    "price": 12.99,
    "oferta": false,
    "description": "Intel LGA 1700 Socket: Supports 13th and 12th Gen Intel Core Series Processors, DDR5 Compatible: 4*SMD DIMMs with XMP 3.0 Memory Module Support",
    "category": "electronics",
    "image": "https://m.media-amazon.com/images/I/81a48Z1GciL._AC_SX679_.jpg",
    }
    ]